function [ Q ] = solveKirchhoff( ) %input R, p
%SOLVEKIRCHHOFF solves a system of equations generated by Kirchhoffs law
%Q: flow rate vector, R: resistance matrix, p: pressure vector
R1=resistanceRectangular(100,40,20,4.1e-3)/10;
R2=resistanceRectangular(30,40,0.50,4.1e-3);
R3=resistanceRectangular(20,40,0.1,4.1e-3)+resistanceRectangular(400,40,10,4.1e-3);
R=[2 1 -1;2*R1 0 R3;0 R2 R3]
p=[0 200 200]; % node, oil-outlet, water-outlet
Q=p/R;

end

